export enum CalendarViewType {
  CalendarView = 'CALENDAR_VIEW',
  CalendarBook = 'CALENDAR_BOOK',
  CalendarBookSelectResource = 'CALENDAR_BOOK_SELECT_RESOURCE',
  CalendarExclusiveBook = 'CALENDAR_EXCLUSIVE_BOOK',
  DayView = 'DAY_VIEW',
  DayViewByLocation = 'DAY_VIEW_BY_LOCATION',
  DayList = 'DAY_LIST',
  List = 'LIST',
  MyEventsList = 'MY_EVENT_LIST',
  MyResourcesList = 'MY_RESOURCES_LIST',
  MyReservationsList = 'MY_RESERVATIONS_LIST',
  MyReservationRequestsList = 'MY_RESERVATION_REQUESTS_LIST',
  ResourceDetail = 'RESOURCE_DETAIL',
  MapResourceList = 'MAP_RESOURCE_LIST',
}